apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: hrms-backend
  name: hrms-backend
spec: 
  type: NodePort
  selector: 
    app: hrms-backend
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
    nodePort: 30081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrms-backend
  template:
    metadata:
      labels:
        app: hrms-backend
    spec:
      containers:
      - name: hrms
        image: micro-hrms:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
