apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:latest
      env:
      - name: POSTGRES_PASSWORD
        value: password
      ports:
      - containerPort: 5432
      
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgres
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
  